apiVersion: v1
data:
  chartName: {{ .Values.foo.bar }}
  {{- if .Values.extra }}
  extraValue: {{ .Values.extra.value }}
  {{- end}}
kind: ConfigMap
metadata:
  name: {{ .Values.name | default "sample" | quote }}
