{{- range $process := .Values.manifest.processes }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $.Values.manifest.name }}-{{ $process.type }}
  labels:
    space: {{ $.Values.manifest.space }}
    version: {{ $.Values.version | quote  }}
spec:
{{- end }}
