coverage:
  status:
    # This is a blocking check
    project:
      default:
        target: auto # Check coverage against the base branch
        threshold: 1% # Allow for a small drop before failing
    # This is an informational check
    patch:
      default:
        target: 75% 
        threshold: 0% 
        informational: true
